# action.yml
name: 'cargo vet'
description: 'The cargo vet subcommand is a tool to help projects ensure that third-party Rust dependencies have been audited by a trusted entity. It strives to be lightweight and easy to integrate. See more at https://mozilla.github.io/cargo-vet'

runs:
  using: 'composite'
  steps:
    - name: cache # should make cargo install faster
      uses: actions/cache@v3
      with:
        path: .cargo/bin/cargo-vet
        key: ${{ runner.os }}-cargo-vet-${{ hashFiles('.cargo/bin/cargo-vet') }}
    - name: cargo vet install
      shell: bash
      run: |
        cargo install --locked cargo-vet
    - name: cargo vet
      shell: bash
      run: |
        # cargo vet will fail if the project did not do "cargo install --locked cargo-vet" and "cargo vet init" first.
        cargo vet
